- name: install agent
  docker_container:
    name: agent
    image: agent:1.0.0
    memory: 1G
    state: started
    user: admin
    network_mode: host
    volumes:
    - /home/admin/agent/agent.yaml:/home/admin/agent/agent.yaml
    - /etc/localtime:/etc/localtime

