# tasks file for roles
- include_tasks: check.yml
- include_tasks: install_agent.yml
  when: not agent_result.exists
- include_tasks: install_logspout.yml
  when: not logspout_result.exists
- include_tasks: install_app.yml
```

check检查agent和logspout容器是否存在（docker_container_info new in ansible 2.8）

```yaml filename=check.yml
- name: Make sure agent container exist
  docker_container_info:  # new in version 2.8
    name: agent
  register: agent_result
- name: Make sure logspout container exist
  docker_container_info:
    name: logspout
  register: logspout_result

